name: Feature request
description: Propose a new capability
title: "feat: "
labels: ["type:feature", "stage:intake"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user problem are we solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
